...@../../../styles/articulate
direction: right

model: Knowledge Model {class: capability}
reasoning: Knowledge Reasoning {class: emphasis}
dcl: "DCL\nCapability behaviour" {class: evidence}
runtime: "Runtime\nExecution" {class: service}

model -> runtime
reasoning -> runtime
dcl -> runtime
