...@../../styles/articulate
direction: right

platform: Messaging Platform {class: evidence}
component: Application Component {class: node}
capability: Business Capability {class: emphasis}

platform -> component: used by
component -> capability: supports
