...@../../../styles/articulate
direction: right

proposal: Proposed Design {class: evidence}
principle: Architectural Principle {class: principle}
availability: Availability Characteristic {class: constraint}
decision: Previous Decision {class: decision}
evaluation: Satisfies or Conflicts? {class: emphasis}
proposal -> evaluation: evaluate
principle -> evaluation: constrains
availability -> evaluation: requires
decision -> evaluation: provides context
