...@../../../styles/articulate
direction: right

question: Replace the messaging platform? {class: evidence}
platform: Messaging Platform {class: node}
component: Dependent Application Components {class: capability}
capability: Supported Business Capabilities {class: emphasis}
decision: Related Decisions {class: decision}
principle: Principles & Characteristics {class: principle}
question -> platform: identify
platform -> component: used by
component -> capability: supports
platform -> decision: selected by
principle -> decision: shaped
