...@../../../styles/articulate
direction: right

architecture: Knowledge Reasoning Architecture {class: evidence}
model: Knowledge Model\nRepresents architectural knowledge {class: data}
layer: Knowledge Reasoning Layer\nExplores and interprets knowledge {class: emphasis}
architecture -> model: representation
architecture -> layer: interpretation
