...@../../../styles/articulate
direction: down

layer: Knowledge Reasoning Layer\nExplores and interprets knowledge {class: emphasis}
model: Knowledge Model\nRepresents connected knowledge {class: data}
layer -> model: reasons with
