...@../../../styles/articulate
direction: right

infrastructure: Infrastructure {class: evidence}
application: Application Component {class: node}
capability: Business Capability {class: emphasis}
infrastructure -> application: hosts
application -> capability: supports
