...@../../../styles/articulate
direction: right

past: Earlier State\nDecision A {class: event}
change: Changed Assumptions {class: evidence}
present: Current State\nDecision B {class: emphasis}
past -> change: valid then
change -> present: explains replacement
