...@../../styles/articulate
direction: right

problem: Problem {class: evidence}
reasoning: Reasoning Capability {class: emphasis}
knowledge: Required Knowledge {class: node}
retrieval: Retrieval Strategy {class: capability}
agent: Agent Behaviour {class: node}

problem -> reasoning -> knowledge -> retrieval -> agent
