...@../../styles/articulate
direction: right

question: Question {class: evidence}
platform: Identify Messaging Platform {class: node}
components: Find Dependent Components {class: node}
capabilities: Identify Supported Capabilities {class: node}
decisions: Examine Related Decisions {class: capability}
principles: Evaluate Relevant Principles {class: capability}
conclusion: Conclusion {class: emphasis}

question -> platform -> components -> capabilities -> decisions -> principles -> conclusion
