...@../../../styles/articulate
grid-rows: 2

problem: Problem {class: evidence}
principles: Principles {class: node}
capabilities: Capabilities {class: emphasis}
architecture: Architecture {class: node}
runtime: Runtime {class: capability}
technology: Technology {class: node}

problem -> principles -> capabilities -> architecture -> runtime -> technology
