...@../../../styles/articulate
direction: right

conversation: Conversation {class: node}
knowledge: Knowledge Model {class: capability}
reasoning: Knowledge Reasoning {class: emphasis}
dcl: DCL {class: evidence}

conversation -> knowledge
knowledge -> reasoning
reasoning -> dcl
