...@../../../styles/articulate
grid-rows: 2

conversation: Conversation {class: node}
discovery: Discovery {class: capability}
knowledge: Knowledge {class: capability}
understanding: Capability Understanding {class: emphasis}
dcl: DCL {class: evidence}

conversation -> discovery -> knowledge -> understanding -> dcl
