...@../../../styles/articulate
grid-rows: 2

conversation: Conversation {class: node}
knowledge: Knowledge {class: capability}
understanding: Understanding {class: emphasis}
intent: Formalised Intent {class: evidence}

conversation -> knowledge -> understanding -> intent
