...@../../../styles/articulate
direction: right

capability: "Capability\nIntent begins to disperse" {class: emphasis}
delivery: "Delivery planning\nRequirements · Backlog" {class: capability}
software: "Software\nSource code · Validation" {class: service}

capability -> delivery
capability -> software
