...@../../../styles/articulate
direction: right

architecture: "Architecture" { class: system }
structure: "Structure" { class: service }
principles: "Principles" { class: principle }
characteristics: "Characteristics" { class: quality }
decisions: "Decisions" { class: decision }
relationships: "Relationships" { class: capability }
constraints: "Constraints" { class: evidence }
evidence: "Evidence" { class: evidence }

structure -> architecture
principles -> architecture
characteristics -> architecture
decisions -> architecture
relationships -> architecture
constraints -> architecture
evidence -> architecture
