# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: knowledge/v1/knowledge.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'knowledge/v1/knowledge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cknowledge/v1/knowledge.proto\x12\x17\x61rticulate.knowledge.v1\"R\n SubmitArchitecturalClaimsRequest\x12.\n\x06\x63laims\x18\x01 \x03(\x0b\x32\x1e.articulate.knowledge.v1.Claim\"L\n!SubmitArchitecturalClaimsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0e\x63\x61ptured_count\x18\x02 \x01(\r\"\xa7\x02\n\x05\x43laim\x12\x11\n\tstatement\x18\x01 \x01(\t\x12\x33\n\x08\x65vidence\x18\x02 \x01(\x0b\x32!.articulate.knowledge.v1.Evidence\x12\x37\n\nprovenance\x18\x03 \x01(\x0b\x32#.articulate.knowledge.v1.Provenance\x12@\n\x0ftemporal_status\x18\x04 \x01(\x0e\x32\'.articulate.knowledge.v1.TemporalStatus\x12\x33\n\x08polarity\x18\x05 \x01(\x0e\x32!.articulate.knowledge.v1.Polarity\x12\x17\n\nconfidence\x18\x06 \x01(\x01H\x00\x88\x01\x01\x42\r\n\x0b_confidence\"\x19\n\x08\x45vidence\x12\r\n\x05value\x18\x01 \x01(\t\"\x1c\n\nProvenance\x12\x0e\n\x06source\x18\x01 \x01(\t*\xcc\x01\n\x0eTemporalStatus\x12\x1f\n\x1bTEMPORAL_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n\x1aTEMPORAL_STATUS_HISTORICAL\x10\x01\x12\x1b\n\x17TEMPORAL_STATUS_CURRENT\x10\x02\x12\x1c\n\x18TEMPORAL_STATUS_EMERGING\x10\x03\x12!\n\x1dTEMPORAL_STATUS_FUTURE_INTENT\x10\x04\x12\x1b\n\x17TEMPORAL_STATUS_UNKNOWN\x10\x05*R\n\x08Polarity\x12\x18\n\x14POLARITY_UNSPECIFIED\x10\x00\x12\x15\n\x11POLARITY_POSITIVE\x10\x01\x12\x15\n\x11POLARITY_NEGATIVE\x10\x02\x32\xa3\x01\n\x0cKnowledgeApi\x12\x92\x01\n\x19SubmitArchitecturalClaims\x12\x39.articulate.knowledge.v1.SubmitArchitecturalClaimsRequest\x1a:.articulate.knowledge.v1.SubmitArchitecturalClaimsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'knowledge.v1.knowledge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPORALSTATUS']._serialized_start=575
  _globals['_TEMPORALSTATUS']._serialized_end=779
  _globals['_POLARITY']._serialized_start=781
  _globals['_POLARITY']._serialized_end=863
  _globals['_SUBMITARCHITECTURALCLAIMSREQUEST']._serialized_start=57
  _globals['_SUBMITARCHITECTURALCLAIMSREQUEST']._serialized_end=139
  _globals['_SUBMITARCHITECTURALCLAIMSRESPONSE']._serialized_start=141
  _globals['_SUBMITARCHITECTURALCLAIMSRESPONSE']._serialized_end=217
  _globals['_CLAIM']._serialized_start=220
  _globals['_CLAIM']._serialized_end=515
  _globals['_EVIDENCE']._serialized_start=517
  _globals['_EVIDENCE']._serialized_end=542
  _globals['_PROVENANCE']._serialized_start=544
  _globals['_PROVENANCE']._serialized_end=572
  _globals['_KNOWLEDGEAPI']._serialized_start=866
  _globals['_KNOWLEDGEAPI']._serialized_end=1029
# @@protoc_insertion_point(module_scope)
