...@../../../diagrams/styles/articulate
direction: right

system: "System" { class: service }
functionality: "What it does" { class: capability }
characteristics: "How well" { class: quality }
qualities: {
  grid-columns: 2
  trust: "Trustworthy" { class: quality }
  reliability: "Reliable" { class: quality }
  performance: "Performant" { class: quality }
  observability: "Observable" { class: quality }
}

system -> functionality: provides
system -> characteristics: possesses
characteristics -> qualities: expressed as
